### ISSUE TITLE
Missing cookie.json

### ISSUE THREAD

**Issue by CasvalDOT** [passbolt/passbolt_cli#34]
Hi, 
after i've installed **node 14** the cli seems no work anymore. 
Each command generated this warning:

`Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`

Each command i run return the following error:

`
{
  errno:-2,
  code:'ENOENT',
  syscall:'open',
  path: '/usr/lib/node_modules/passbolt_cli/app/tmp/cookie.json'
}
`

I've created manuallty the tmp folder adding a blank file called cookie.json, and then I've change the ownership of the folder:

`sudo chown -R <my_user>:<my_user>  /usr/lib/node_modules/passbolt_cli/app/tmp`

now it works again, but I supposed this is not the correct behavior. I've forgot something in the configuration procedure or it is a bug?

PS. the passbolt_cli is installed globally

**Comment by stripthis** [comment]
Hi there,

Sorry for the late reply, by default you should have a app/tmp directory created, as there is a file named "[empty](https://github.com/passbolt/passbolt_cli/blob/master/app/tmp/empty)", as placeholder. Maybe your issue was that it was not writable by the user using passbolt cli globally?

**Comment by CasvalDOT** [comment]
Thanks for the reply and sorry for the late answer. Surely my user has not write permission to /usr folder running the CLI (probabily only with sudo it can write in /usr directory). I don't know if this folder should be created during installation process. Maybe is better create this folder in user home directory instead. What do you think? This should prevent this behavior.

**Comment by almereyda** [comment]
This also happened to me with a global install, yet within an NVM environment:

```shell
$ passbolt auth login
/home/yala/.nvm/versions/node/v14.18.2/lib/node_modules/passbolt_cli/node_modules/tough-cookie-file-store/lib/file-store.js:214
        if (err) throw err;
                 ^

[Error: ENOENT: no such file or directory, open '/home/yala/.nvm/versions/node/v14.18.2/lib/node_modules/passbolt_cli/app/tmp/cookie.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/yala/.nvm/versions/node/v14.18.2/lib/node_modules/passbolt_cli/app/tmp/cookie.json'
}
```

Creating the `tmp` directory directory was sufficient for this to continue to work:

```shell
$ mkdir /home/yala/.nvm/versions/node/v14.18.2/lib/node_modules/passbolt_cli/app/tmp
$ passbolt auth login
$ ls /home/yala/.nvm/versions/node/v14.18.2/lib/node_modules/passbolt_cli/app/tmp
cookie.json
```

It appears this is a packaging failure, as the node_modules directories should not be written other than by NPM, and we have explicitly created a `~/.config/passbolt/` directory during setup, where such transitory data could also be kept.

**Comment by mmospanenko** [comment]
I have the same issue. When running `passbolt auth`, I get an "Error [ERR_REQUIRE_ESM]: require() of ES Module tough-cookie-file-store not supported" with Node.js v18.19.0. Looks like the module import needs to be updated to use dynamic import().

```bash
root@63ab8244ab5f:/usr/share/php/passbolt/passbolt_cli# passbolt auth
/usr/share/php/passbolt/passbolt_cli/app/controllers/gpgAuthController.js:15
const CookieStore = require('tough-cookie-file-store');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/share/php/passbolt/passbolt_cli/node_modules/tough-cookie-file-store/dist/cookie-file-store.js from /usr/share/php/passbolt/passbolt_cli/app/controllers/gpgAuthController.js not supported.
Instead change the require of cookie-file-store.js in /usr/share/php/passbolt/passbolt_cli/app/controllers/gpgAuthController.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/share/php/passbolt/passbolt_cli/app/controllers/gpgAuthController.js:15:21)
    at Object.<anonymous> (/usr/share/php/passbolt/passbolt_cli/passbolt-auth.js:14:27) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.19.0
```
